### ISSUE TITLE
Changes needed in the GUI

### ISSUE THREAD

**Issue by ACovaci99** [ACovaci99/I_Love_Science_Fest#15]
These need to  be done to accommodate for the Camera class:

- line 14 should be changed to:  from camera_capture import Camera()
- in the __init__() the following line should be placed: self.camera = Camera()
- line 106 should be changed to: new_image = self.camera.capture_img_new('image_1.png')
- line 157 needs to be commented out.

**Comment by hosseindehghanipour1998** [comment]
The whole code for the camera is changed now. Check [Video Window](https://github.com/ACovaci99/I_Love_Science_Fest/blob/167949eaf90f6cf62c8b5c2bebf657f7773c09b3/GUI/hd_utility.py#L184)
