### ISSUE TITLE
pdf to image 

### ISSUE THREAD

**Issue by ACovaci99** [ACovaci99/I_Love_Science_Fest#18]
I attempted to use that pdf2image package but kept getting errors. I looked into alternatives and found this package which did work on my half. I would recommend using this one. 
![MicrosoftTeams-image (3)](https://github.com/ACovaci99/I_Love_Science_Fest/assets/118910836/c2ffc951-a591-489b-9224-108626ac1de1)

**Comment by hosseindehghanipour1998** [comment]
Feature added!
